name: .NET Core

on: [push]

jobs:
  universal_windows_build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build DotNET35
      run: |
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe $Env:GITHUB_WORKSPACE\src\MiunieWindows.sln -t:restore
           .\MSBuild.exe $Env:GITHUB_WORKSPACE\src\MiunieWindows.sln /p:Configuration=Release /p:UapAppxPackageBuildMode=StoreUpload
